[package]
name = "nixie"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Bare metal provisioning engine for NixOS"

[lib]
name = "nixie"
path = "src/lib.rs"

[[bin]]
name = "nixie"
path = "src/bin/nixie.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
dhcproto = "0.15"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tiny_http = "0.12"
macaddr = "1"
sha2 = "0.10"
hmac = "0.12"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
dhcproto = "0.15"
macaddr = "1"
